version: '3'
services:
#  gateway:
#    build:
#      context: .
#      dockerfile: Dockerfile.gateway
#    environment:
#    - ENV=DEVELOPMENT
#    - REDIS_URL=j
  lavalink:
    container_name: lavalink
    image: fredboat/lavalink:master
    ports:
      - "8080:8080"
    volumes:
      - lavalink:/opt/Lavalink
      - ${PWD}/lavalink.yml:/opt/Lavalink/application.yml
  redis:
    container_name: hifumi_redis
    image: redis
    ports:
    - "6379:6379"
  postgres:
    container_name: hifumi_postgres
    image: postgres:10.3
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    ports:
    - "${TYPEORM_PORT}:5432"
    environment:
    - POSTGRES_DB=hifumi
    - POSTGRES_USER=hifumi
    - POSTGRES_PASSWORD=eagle_jump
    volumes:
    - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
  lavalink:
