CREATE DATABASE hifumi;
CREATE ROLE "typeorm-client" WITH
	LOGIN
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT 5
	PASSWORD 'hifumi';
GRANT ALL PRIVILEGES ON DATABASE hifumi TO "typeorm-client";
